version: "3.7"
services:
  # Layanan untuk Laravel/PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: always
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - app-network

  # Layanan untuk Nginx (Web Server)
  web:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  # Layanan untuk MySQL (Database)
  db:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      # Mengambil nilai dari .env file di host
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Asumsi Anda punya variabel ini
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

# Volume untuk data persisten database
volumes:
  db-data:

# Jaringan
networks:
  app-network:
    driver: bridge

docker run -d\
  --name mysql8\
  -e MYSQL_ROOT_PASSWORD=vibtech2025\
  -e MYSQL_DATABASE=vibtech_crm_dev_db\
  -p 3308:3306\
  mysql:8